### ISSUE TITLE
OSError: dlopen() failed to load a library: cairo / cairo-2

### ISSUE THREAD

**Issue by vvscode** [icoz/habraparse#11]
I'm on master branch (at `d519e4d8343982715cdc140030e8d2deec8c115f` - current HEAD )
```
vvs@ ~/r/habraparse> python3 habraparse.py save_post 146039                                                  23:32:30
Traceback (most recent call last):
  File "habraparse.py", line 7, in <module>
    from weasyprint import HTML, CSS
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/weasyprint/__init__.py", line 359, in <module>
    from .css import PARSER, preprocess_stylesheet  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/weasyprint/css/__init__.py", line 30, in <module>
    from . import computed_values
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/weasyprint/css/computed_values.py", line 18, in <module>
    from .. import text
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/weasyprint/text.py", line 20, in <module>
    import cairocffi as cairo
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cairocffi/__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cairocffi/__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2
```

before I setup packages via instructions. And after upgrade the same result

```
vvs@ ~/r/habraparse> sudo pip3 install --upgrade -r requirements.txt                                         23:32:01
Requirement already up-to-date: cairocffi==0.7.2 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: CairoSVG==2.0.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: cffi==1.9.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cssselect==1.0.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: docopt==0.6.2 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: html5lib==0.999999999 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: lxml==3.7.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: Pillow==3.4.2 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: pycparser==2.17 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: Pyphen==0.9.4 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: requests==2.12.3 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: six==1.10.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: tinycss==0.4 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: WeasyPrint==0.33 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: webencodings==0.5 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: setuptools>=18.5 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from html5lib==0.999999999->-r requirements.txt (line 6))
```

**Comment by icoz** [comment]
Sorry, but I think that problem is in weasyprint. Can you tell me post ID,
which gives you error?

**Comment by vvscode** [comment]
Sure

Post id is `146039`

`https://habrahabr.ru/post/146039/`

**Comment by icoz** [comment]
Я не могу воспроизвести эту ошибку. Проверьте ещё раз на чистой установке (например, через virtualenv).

**Comment by vvscode** [comment]
На сколько я понимаю - тоже самое
```bash
bash-3.2$ source ~/venv/habraparse/bin/activate
(habraparse) bash-3.2$ cd
(habraparse) bash-3.2$ cd repo
(habraparse) bash-3.2$ cd habraparse/
(habraparse) bash-3.2$ pip --version
pip 9.0.1 from /Users/vvs/venv/habraparse/lib/python3.5/site-packages (python 3.5)
(habraparse) bash-3.2$ pip install -r requirements.txt
Collecting cairocffi==0.7.2 (from -r requirements.txt (line 1))
  Using cached cairocffi-0.7.2.tar.gz
Collecting CairoSVG==2.0.0 (from -r requirements.txt (line 2))
  Using cached CairoSVG-2.0.0-py3-none-any.whl
Collecting cffi==1.9.1 (from -r requirements.txt (line 3))
  Using cached cffi-1.9.1-cp35-cp35m-macosx_10_10_x86_64.whl
Collecting cssselect==1.0.0 (from -r requirements.txt (line 4))
  Using cached cssselect-1.0.0-py2.py3-none-any.whl
Collecting docopt==0.6.2 (from -r requirements.txt (line 5))
  Using cached docopt-0.6.2.tar.gz
Collecting html5lib==0.999999999 (from -r requirements.txt (line 6))
  Using cached html5lib-0.999999999-py2.py3-none-any.whl
Collecting lxml==3.7.0 (from -r requirements.txt (line 7))
  Using cached lxml-3.7.0.tar.gz
Collecting Pillow==3.4.2 (from -r requirements.txt (line 8))
  Downloading Pillow-3.4.2-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.4MB)
    100% |████████████████████████████████| 3.5MB 372kB/s
Collecting pycparser==2.17 (from -r requirements.txt (line 9))
  Using cached pycparser-2.17.tar.gz
Collecting Pyphen==0.9.4 (from -r requirements.txt (line 10))
  Using cached Pyphen-0.9.4-py2.py3-none-any.whl
Collecting requests==2.12.3 (from -r requirements.txt (line 11))
  Using cached requests-2.12.3-py2.py3-none-any.whl
Collecting six==1.10.0 (from -r requirements.txt (line 12))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting tinycss==0.4 (from -r requirements.txt (line 13))
  Using cached tinycss-0.4.tar.gz
Collecting WeasyPrint==0.33 (from -r requirements.txt (line 14))
  Using cached WeasyPrint-0.33-py3-none-any.whl
Collecting webencodings==0.5 (from -r requirements.txt (line 15))
  Using cached webencodings-0.5.tar.gz
Requirement already satisfied: setuptools>=18.5 in /Users/vvs/venv/habraparse/lib/python3.5/site-packages (from html5lib==0.999999999->-r requirements.txt (line 6))
Building wheels for collected packages: cairocffi, docopt, lxml, pycparser, tinycss, webencodings
  Running setup.py bdist_wheel for cairocffi ... done
  Stored in directory: /Users/vvs/Library/Caches/pip/wheels/68/f5/be/c51d75052e759f21f0d7e5b8ad8770b19c9ab35f2942e21bb9
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /Users/vvs/Library/Caches/pip/wheels/b2/16/5f/c33a2bb5f2dce71205f8e65cbfd05647d79d441282be31fd82
  Running setup.py bdist_wheel for lxml ... done
  Stored in directory: /Users/vvs/Library/Caches/pip/wheels/b1/6c/fb/5453b393a084672d8b42e59aec63eafeae4a2c2e1c5dd2485f
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /Users/vvs/Library/Caches/pip/wheels/a8/0b/41/dc95621f9d3a0da7bc191b8a71f0e8182ffd3cc5f33ac55005
  Running setup.py bdist_wheel for tinycss ... done
  Stored in directory: /Users/vvs/Library/Caches/pip/wheels/69/61/24/a0adf0f68efd99274624418936dfe835bca04537d62eb18280
  Running setup.py bdist_wheel for webencodings ... done
  Stored in directory: /Users/vvs/Library/Caches/pip/wheels/0a/73/c2/1dcc99951b6aeac495e7695505d1837616ca194938f07d1d7b
Successfully built cairocffi docopt lxml pycparser tinycss webencodings
Installing collected packages: pycparser, cffi, cairocffi, Pillow, lxml, cssselect, tinycss, CairoSVG, docopt, six, webencodings, html5lib, Pyphen, requests, WeasyPrint
Successfully installed CairoSVG-2.0.0 Pillow-3.4.2 Pyphen-0.9.4 WeasyPrint-0.33 cairocffi-0.7.2 cffi-1.9.1 cssselect-1.0.0 docopt-0.6.2 html5lib-0.999999999 lxml-3.7.0 pycparser-2.17 requests-2.12.3 six-1.10.0 tinycss-0.4 webencodings-0.5
(habraparse) bash-3.2$ ./habraparse.py save_post 146039
Traceback (most recent call last):
  File "./habraparse.py", line 7, in <module>
    from weasyprint import HTML, CSS
  File "/Users/vvs/venv/habraparse/lib/python3.5/site-packages/weasyprint/__init__.py", line 359, in <module>
    from .css import PARSER, preprocess_stylesheet  # noqa
  File "/Users/vvs/venv/habraparse/lib/python3.5/site-packages/weasyprint/css/__init__.py", line 30, in <module>
    from . import computed_values
  File "/Users/vvs/venv/habraparse/lib/python3.5/site-packages/weasyprint/css/computed_values.py", line 18, in <module>
    from .. import text
  File "/Users/vvs/venv/habraparse/lib/python3.5/site-packages/weasyprint/text.py", line 20, in <module>
    import cairocffi as cairo
  File "/Users/vvs/venv/habraparse/lib/python3.5/site-packages/cairocffi/__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "/Users/vvs/venv/habraparse/lib/python3.5/site-packages/cairocffi/__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2
(habraparse) bash-3.2$
```

Но с учетом работающего докер-варианта вопрос не критичен )

**Comment by icoz** [comment]
Эммм... А попробуйте вместо 
./habraparse.py save_post 146039
Набрать 
./habraparse.py save_post 146039 out.pdf

**Comment by vvscode** [comment]
Тоже самое

может мне создать `relocatable` venv и приложить его сюда?

**Comment by icoz** [comment]
Я подозреваю, что ошибка где-то внутри библиотек. Причём, возможно, что конфликты именно в вашей системе. Я так глубоко не полезу.
Проблема не моей программы. Так что закрываю.
Если вдруг у кого-то повторится, тогда будем думать ещё раз.
