### ISSUE TITLE
habr.topic.PostDeleted for existing post on using docker version

### ISSUE THREAD

**Issue by vvscode** [icoz/habraparse#12]
I just download docker container
```docker pull icoz/habraparse```

For url `https://habrahabr.ru/post/146039/` I try run 

```
docker run -it -v /Users/vvs/tmp:/data icoz/habraparse save_post 146039 /data/146039.pdf
```
but got next 

```
Traceback (most recent call last):
  File "/habraparse/habraparse.py", line 259, in <module>
    main()
  File "/habraparse/habraparse.py", line 238, in main
    save_pdf(t_id, filename=fname, with_comments=args['--with-comments'], project=project)
  File "/habraparse/habraparse.py", line 105, in save_pdf
    ht = HabraTopic(topic_id)
  File "/habraparse/habr/topic.py", line 93, in __init__
    super().__init__(topic_id, domain='habrahabr.ru')
  File "/habraparse/habr/topic.py", line 27, in __init__
    self._parseTopic()
  File "/habraparse/habr/topic.py", line 52, in _parseTopic
    raise PostDeleted
habr.topic.PostDeleted
```

**Comment by icoz** [comment]
Can we speak in Russian?
А можно по-русски?
Думаю, что надо добавить проверку. По факту эта ошибка говорит о том, что
поста нет. Удалён или заблокирован

14 янв. 2017 г. 23:46 пользователь "Vasiliy Vanchuk" <
notifications@github.com> написал:

**Comment by vvscode** [comment]
Можно)
Пост есть - я для этого и привел ссылку.

**Comment by vvscode** [comment]
он открыт у меня в браузере и я просто хотел на нем проверить как смотрятся картинки и код в получаемом документе

**Comment by icoz** [comment]
Смотрятся не очень, так как зависят от CSS, которые нынче написаны так, чтобы это всё плохо рендерилось. Я так понимаю, специально борются.
Надо написать свои какие-то CSS, но я в этом не мастак. Помочь пока никто не собрался.

**Comment by icoz** [comment]
Специально поставил новое тестовое окружение. У меня всё норм. Есть pdf-файл. Есть картинки в нем.
А вот докер я давно не пересобирал. Поставьте себе из репозитория версию.

**Comment by icoz** [comment]
Обновил контейнер. Проверил. На конкретно этой статье работает.
По результатам отпишитесь, закрою проблему.

**Comment by vvscode** [comment]
```
vvs@ ~/r/habraparse> docker pull icoz/habraparse                                                             11:08:01
Using default tag: latest
latest: Pulling from icoz/habraparse

75a822cd7888: Pull complete
57de64c72267: Pull complete
4306be1e8943: Pull complete
871436ab7225: Pull complete
37c937b0ca47: Pull complete
8d54cb978e38: Pull complete
ecd423deff51: Pull complete
6317fdeaa07e: Pull complete
Digest: sha256:11b390616758339f34cad2696294a51dc5203e3203012e47f98f0ce035151aeb
Status: Downloaded newer image for icoz/habraparse:latest
vvs@ ~/r/habraparse> docker run -it -v /Users/vvs/tmp:/data icoz/habraparse save_post 146039 /data/146039.pdf
WARNING: @font-face support needs Pango >= 1.38
/usr/local/lib/python3.6/site-packages/cairocffi/surfaces.py:651: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  ffi.cast('char*', address), format, width, height, stride)
/usr/local/lib/python3.6/site-packages/cairocffi/surfaces.py:447: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  *keep_alive.closure))
```

но файл  я все же получил. Лог привожу на случай, если эти warning что-то да значат важное

Спасибо

**Comment by icoz** [comment]
А warning говорит о том,  что в библиотеке меняется api. И что скоро той функции, что вы дергаете, не будет.
