### ISSUE TITLE
Падение при определении даты регистрации

### ISSUE THREAD

**Issue by burashka** [icoz/habraparse#3]
При запуске с ключами для GT или MM скрипт валится с ошибкой

```
# ./habraparse.py save_favs --mm buranLcme ../posts/MegaMozg
Traceback (most recent call last):
  File "./habraparse.py", line 252, in <module>
    main()
  File "./habraparse.py", line 223, in main
    limit=args['--limit'], project=project)
  File "./habraparse.py", line 120, in save_all_favs_for_user
    hu = MegamozgUser(username)
  File "/home/burashka/habraparse/habr/user.py", line 239, in __init__
    super().__init__(username, need_favorites, need_user_posts=need_user_posts, domain='megamozg.ru')
  File "/home/burashka/habraparse/habr/user.py", line 35, in __init__
    self._parseUserpage()
  File "/home/burashka/habraparse/habr/user.py", line 154, in _parseUserpage
    self._user_profile['registration_date'] = date_of_registration[:date_of_registration.index('\r\n')]
ValueError: substring not found
```

закомментаривание 154ой строки спасает ситуацию.

**Comment by icoz** [comment]
Вас понял, буду разбираться.

**Comment by icoz** [comment]
Починил.
