### ISSUE TITLE
Падение скрипта

### ISSUE THREAD

**Issue by xvitaly** [icoz/habraparse#4]
Падает при запуске:

```
[user4@localhost habraparse]$ python3 habraparse.py save_favs -c USERNAME /tmp/habr/
Traceback (most recent call last):
  File "habraparse.py", line 252, in <module>
    main()
  File "habraparse.py", line 223, in main
    limit=args['--limit'], project=project)
  File "habraparse.py", line 122, in save_all_favs_for_user
    hu = HabraUser(username)
  File "/home/vitaly/git/habraparse/habr/user.py", line 229, in __init__
    super().__init__(username, need_favorites, need_user_posts=need_user_posts, domain='habrahabr.ru')
  File "/home/vitaly/git/habraparse/habr/user.py", line 35, in __init__
    self._parseUserpage()
  File "/home/vitaly/git/habraparse/habr/user.py", line 154, in _parseUserpage
    self._user_profile['registration_date'] = date_of_registration[:date_of_registration.index('\n')].strip()
ValueError: substring not found
```

USERNAME - логин любого пользователя HH.

Версия Python3:

```
[user4@localhost habraparse]$ python3 --version
Python 3.4.1
```

**Comment by icoz** [comment]
Подозреваю, что дело в винде. Под нее не тестил.
22 апр. 2015 г. 17:25 пользователь "V1TSK" notifications@github.com
написал:

**Comment by xvitaly** [comment]
У меня GNU/Linux. Дистрибутив Fedora.

**Comment by icoz** [comment]
Исправил, потестил. Вроде всё ок. Баг закрываю.
